import Foundation
import XCTest
@testable import GoEngine

final class GoEngineTests: XCTestCase {
    struct Case: Decodable {
        let moves: [Int]
        let board: [Int8]
        let ko: Int
        let to_play: Int8
        let legal: [Int]
        let score: Double
        let features_sum: [Float]
        let features_hash: Int
    }

    struct Vectors: Decodable { let cases: [Case] }

    /// Replays random games generated by the Python rules and checks every
    /// board, ko point, legal-move mask, score and feature plane matches.
    func testParityWithPythonRules() throws {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "test_vectors", withExtension: "json"))
        let vectors = try JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
        XCTAssertGreaterThan(vectors.cases.count, 100)
        for (i, c) in vectors.cases.enumerated() {
            var pos = Position()
            for m in c.moves {
                XCTAssertTrue(pos.isLegal(m), "case \(i): illegal \(m)")
                pos = pos.play(m)
            }
            XCTAssertEqual(pos.board, c.board, "case \(i) board")
            XCTAssertEqual(pos.ko, c.ko, "case \(i) ko")
            XCTAssertEqual(pos.toPlay.rawValue, c.to_play, "case \(i) to play")
            XCTAssertEqual(pos.legalMask().map { $0 ? 1 : 0 }, c.legal, "case \(i) legal")
            XCTAssertEqual(pos.areaScore(), c.score, "case \(i) score")
            let f = pos.features()
            let sums = (0..<6).map { k in f[(k * 81)..<((k + 1) * 81)].reduce(0, +) }
            XCTAssertEqual(sums, c.features_sum, "case \(i) feature sums")
            let hash = f.enumerated().reduce(0) { $0 + Int($1.element) * $1.offset }
            XCTAssertEqual(hash, c.features_hash, "case \(i) feature layout")
        }
    }

    func testKoAndCapture() {
        // Black A9 B8 C9, white C8 D9; white B9 captures C9 and creates a ko.
        var b = [Int8](repeating: 0, count: 81)
        for p in [0, 10, 2] { b[p] = 1 }
        for p in [11, 3] { b[p] = -1 }
        let pos = Position(board: b, prevBoard: b, toPlay: .white, ko: -1, passes: 0, moveCount: 0)
        let after = pos.play(1)
        XCTAssertEqual(after.board[2], 0)
        XCTAssertEqual(after.ko, 2)
        XCTAssertFalse(after.isLegal(2))
    }

    func testSearchFindsWinningPass() throws {
        // White just passed and black owns the board (wall on column E): passing wins.
        var b = [Int8](repeating: 0, count: 81)
        for r in 0..<9 { b[r * 9 + 4] = 1 }
        let pos = Position(board: b, prevBoard: b, toPlay: .black, ko: -1, passes: 1, moveCount: 9)
        let mcts = MCTS(evaluator: UniformEvaluator(), position: pos)
        try mcts.search(300)
        XCTAssertEqual(mcts.bestMove(), Go.pass)
        XCTAssertEqual(mcts.snapshot().simulations, 300)
    }

    func testTwoPassesEndGameWhiteWinsEmptyBoard() {
        let p = Position().play(Go.pass).play(Go.pass)
        XCTAssertTrue(p.isOver)
        XCTAssertEqual(p.winner(), .white)
        XCTAssertEqual(Go.moveName(0), "A9")
        XCTAssertEqual(Go.moveName(80), "J1")
    }
}
